### ISSUE TITLE
What is the minmum Width & Height?

### ISSUE THREAD

**Issue by rksambari** [ushelp/EasyQRCodeJS#83] opened 2022-11-14 06:37 UTC
Hi,

When I give smaller sizes like 24x24 px, It is not giving proper results.
And also there is a slight size mismatch of the result QR code with respect to the width and height provided as part of request.

Thanks.

**Comment by ushelp** [comment] 2023-09-28 08:51
Duplicate of #18  #63 #61

**Closed by ushelp** 2023-09-28 08:51 UTC
