### ISSUE TITLE
width and height not respected based on QR text

### ISSUE THREAD

**Issue by chimmelb** [ushelp/EasyQRCodeJS#61] opened 2021-07-06 17:59 UTC
When my QR code text is `http://app.localhost:8080/#/qr/3ef8c213-7065-41ff-aaf8-da47825b9834`, my QR code renders like this:
![image](https://user-images.githubusercontent.com/5881179/124645406-643f5c00-de61-11eb-9eb1-ef8ecb866311.png)

But when the QR code text is `https://testapp.abcdefghijklmno.com/#/qr/7a0e83b8-7f2f-42a5-9f1b-bc6c857035d2`, it renders like this: 
![image](https://user-images.githubusercontent.com/5881179/124645685-b97b6d80-de61-11eb-9b75-e1ece585e40f.png)

This is only changing the `text` property via the `linkUrl` variable. The QR code is generated like this:

```
        this.qrObjects[code] = new QRCode(this.$refs[code], {
          text: linkUrl, // Content
          width: 180, // Widht
          height: 180, // Height
          quietZone: 14,
          colorDark: '#000000', // Dark color
          colorLight: '#ffffff', // Light color
          correctLevel: QRCode.CorrectLevel.Q, // L, M, Q, H
          title: 'powered by Title', // content
          titleTop: 176,
          titleFont: 'normal normal normal 12px Arial',
          titleColor: '#4F4F4F'
        })
```

(which is in VueJS, and there can be many QR codes on the page, so they are tracked individually)

Why might the QR render out of bounds like that? I was surprised when things worked on my development machine perfectly, and then did not on our staging server. I thought it might have been CSS at first, but it's just the URL of the link!

This is version 4.4.3.

**Comment by ushelp** [comment] 2021-07-09 08:29
Duplicate of #18 

There is a basic principle. To maintain the precise size of the QRCode, it needs to be calculated as needed. Otherwise, the program will round unreasonable values. the reason: 
https://github.com/ushelp/EasyQRCodeJS/issues/18#issuecomment-635323029

**Comment by chimmelb** [comment] 2021-07-14 13:56
Is there a way to know how many blocks will be used? Is it dependent on the number of characters of the QR's text? 

This can be closed as it is intended behavior. For my purposes, I put the title on the top instead of the bottom (though the bottom was my first preference)

**Comment by ushelp** [comment] 2021-07-16 01:27
The number of blocks depends on the QRCode version corresponding to the character length. 

For you reference:
https://www.qrcode.com/en/about/version.html

![图片](https://user-images.githubusercontent.com/4082017/125797763-4388c941-3124-4f0f-8b0a-3e5f615dfb1c.png)

**Closed** 2021-07-19 07:38 UTC
