### ISSUE TITLE
width and height are not accurate

### ISSUE THREAD

**Issue by now915** [ushelp/EasyQRCodeJS#63] opened 2021-08-03 15:06 UTC
I set qrcode options { width: 430, heigth: 430 }, and generate it. But the canvas's width  and height 
are 444px in HTML, so do the other width and height which setted in options.

How  can I generate a accurate qrcode witdh  easyqrcodejs...

I use vue and  the version of easyqrcodejs is 4.4.3

**Comment by ushelp** [comment] 2021-08-04 07:19
Duplicate of #18 #61

**Closed** 2021-08-28 03:51 UTC
